title: The personal web site of Siddharth Maddali
email: siddharthmv@gmail.com
description: >-
    Physicist working on imaging and characterization techniques for condensed matter systems. 
baseurl: "/"
url: "https://siddharth-maddali.github.io"
twitter_username: SidDarthious
github_username:  siddharth-maddali
google_cse_id: 017891795388792712943:lhqxlsyf4-8
permalink: /:categories/:year/:month/:day/:title:output_ext
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
 
